spring:
  datasource:
    url: jdbc:mysql://10.3.33.188:3306/qa_charity_x?useUnicode=true&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: sit-1217
    hikari:
      maximum-pool-size: 4

  data:
    redis:
      cluster:
        nodes:
          - 10.3.33.188:7001

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


oauth:
  redirect-url: http://localhost:3000